# Docker compose file for docker-metrics-collector

version: '3'
services:
  elk:
    image: sebp/elk:622
    container_name: elk
    ports:
      - 5601:5601 # kibana
      - 9200:9200 # elasticsearch
      # - 5044:5044 # logstash - not using
    environment:
      - "MAX_MAP_COUNT=${MAX_MAP_COUNT}"
    # Uncomment the line below to persist log data
    #volumes:                                                           #PERSIST_DATA
    #  - "${HOME}/.cwlmetrics/data/elk/elk-data":/var/lib/elasticsearch #PERSIST_DATA

  run-dmc:
    image: quay.io/inutano/run-dmc:0.1.0
    container_name: run-dmc
    environment:
      - "ES_HOST=${ES_HOST}"
      - "ES_PORT=${ES_PORT}"
    volumes:
      - .:/work

  fluentd:
    depends_on:
      - run-dmc
    image: quay.io/inutano/fluentd:0.1.0
    container_name: fluentd
    environment:
      - "ES_HOST=${ES_HOST}"
      - "ES_PORT=${ES_PORT}"
    volumes:
      - ./log/telegraf:/var/log/telegraf
      - ./conf/fluent/fluent.conf:/etc/fluent/fluent.conf:ro
      - ./log/fluentd:/var/log/fluentd
    command:
      - "fluentd"
      - "--log"
      - "/var/log/fluentd/fluentd.log"

  telegraf:
    depends_on:
      - run-dmc
      - fluentd
    image: telegraf:1.5.0-alpine
    container_name: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./log/telegraf:/var/log/telegraf
