# Docker compose file for docker-metrics-collector

version: '3'
services:
  elk:
    image: sebp/elk:622
    container_name: elk
    ports:
      - 5601:5601 # kibana
      - 9200:9200 # elasticsearch
      # - 5044:5044 # logstash - not using
    environment:
      - MAX_MAP_COUNT=262144 # setting for docker4mac

  dmc-setup:
    depends_on:
      - elk
    image: inutano/dmc-setup:alpha
    container_name: dmc-setup
    environment:
      - ES_HOST=elk
      - ES_PORT=9200
    volumes:
      - .:/work

  telegraf:
    depends_on:
      - dmc-setup
    image: telegraf:1.5.0-alpine
    container_name: telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./log/telegraf:/var/log/telegraf

  fluentd:
    depends_on:
      - dmc-setup
    image: inutano/fluentd:alpha
    container_name: fluentd
    environment:
      - ES_HOST=elk
      - ES_PORT=9200
    volumes:
      - ./log/telegraf:/var/log/telegraf
      - ./conf/fluent/fluent.conf:/etc/fluent/fluent.conf:ro
      - ./log/fluentd:/var/log/fluentd
    command:
      - "fluentd"
      - "--log"
      - "/var/log/fluentd/fluentd.log"
